import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// 1. Generate src/embeddedAssets.ts from relay.py and strings.json
const relayPy = fs.readFileSync(path.join(__dirname, 'relay.py'), 'utf8');
const stringsJson = fs.readFileSync(path.join(__dirname, 'strings.json'), 'utf8');

const embeddedContent = `// Auto-generated by esbuild.config.mjs during build. Do not edit manually.
export const EMBEDDED_RELAY_PY = ${JSON.stringify(relayPy)};
export const EMBEDDED_STRINGS_JSON = ${JSON.stringify(stringsJson)};
`;

fs.writeFileSync(path.join(__dirname, 'src', 'embeddedAssets.ts'), embeddedContent, 'utf8');

// 2. Sync manifest.json to repository root (required by Obsidian community plugins CI)
const manifestContent = fs.readFileSync(path.join(__dirname, 'manifest.json'), 'utf8');
fs.writeFileSync(path.join(__dirname, '..', 'manifest.json'), manifestContent, 'utf8');

// 3. Build bundle
await esbuild.build({
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian', 'electron', 'http', 'crypto', '@codemirror/*', '@lezer/*'],
  format: 'cjs',
  target: 'es2020',
  platform: 'node',
  outfile: 'main.js',
  sourcemap: false,
  treeShaking: true,
});

console.log('claudian-wechat: build complete -> main.js (with self-extracting embedded assets)');
